# Generated by Django 4.1.5 on 2023-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_realvedic_app', '0004_alter_actionlogs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
            field=models.TextField(default='2023-10-06 13:20:38.353606+05:30'),
        ),
    ]
