# Generated by Django 4.1.5 on 2023-10-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0077_shipping_price_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-10-06 13:19:46.229488+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-10-06 13:19:46.229488+05:30'),
        ),
    ]
